# Generated by Django 3.2.12 on 2022-03-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomersCustomers',
            new_name='customers',
        ),
    ]
