# Generated by Django 3.2.12 on 2022-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('transporterId', models.IntegerField()),
                ('amount', models.FloatField(blank=True, default='0', null=True)),
                ('driverstatus', models.IntegerField(default='0')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delete', models.SmallIntegerField(default='0')),
            ],
        ),
    ]
