# Generated by Django 3.2.12 on 2022-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField(blank=True, null=True)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('accountname', models.CharField(blank=True, max_length=255, null=True)),
                ('accountnumber', models.BigIntegerField(blank=True, null=True)),
                ('ifccode', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delete', models.SmallIntegerField(default='0')),
            ],
        ),
    ]
