# Generated by Django 4.0.1 on 2022-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.BigIntegerField(blank=True, db_column='orderId', null=True)),
                ('userId', models.BigIntegerField(blank=True, null=True)),
                ('transporterid', models.BigIntegerField(blank=True, null=True)),
                ('messagetype', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('messagetime', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delete', models.SmallIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcity', models.CharField(max_length=250)),
                ('tocity', models.CharField(max_length=250)),
                ('userId', models.IntegerField(default='0')),
                ('transporterId', models.IntegerField(default='0')),
                ('orderDescription', models.TextField(blank=True, null=True)),
                ('statusFromUser', models.SmallIntegerField(default='0')),
                ('OrderStatus', models.SmallIntegerField(default='0')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delete', models.SmallIntegerField(default='0')),
                ('fromlatitude', models.CharField(blank=True, max_length=50, null=True)),
                ('fromlongitude', models.CharField(blank=True, max_length=50, null=True)),
                ('tolatitude', models.CharField(blank=True, max_length=50, null=True)),
                ('tolongitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
